apiVersion: v1
kind: Namespace
metadata:
  name: scenario-01a-ns
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-b-sa
  namespace: scenario-01a-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a-sa
  namespace: scenario-01a-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deploy
  namespace: scenario-01a-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
      version: 0.0.1
  template:
    metadata:
      labels:
        app: service-b
        version: 0.0.1
    spec:
      serviceAccountName: service-b-sa
      containers:
      - name: service-b-co
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: scenario-01a-ns
spec:
  selector:
    app: service-b
    version: 0.0.1
  ports:
  - name: service-b-http-port
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: api-company-com-service-entry
  namespace: scenario-01a-ns
spec:
  hosts:
    - api.company.com
  location: MESH_INTERNAL
  resolution: STATIC
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deploy
  namespace: scenario-01a-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
      version: 0.0.1
  template:
    metadata:
      labels:
        app: service-a
        version: 0.0.1
    spec:
      serviceAccountName: service-a-sa
      containers:
      - name: service-a-co
        image: curlimages/curl
        command: ["/bin/sh"]
        args: ["-c", "while curl http://api.company.com/uuid; do sleep 1.0; done;"]
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-company-com-virtual-service
  namespace: scenario-01a-ns
spec:
  hosts:
    - api.company.com
  http:
    - name: service-b-http-route
      match:
        - method:
            exact: GET
          headers:
            host:
              exact: api.company.com
          uri:
            exact: /uuid
      route:
        - destination:
            host: service-b.scenario-01a-ns.svc.cluster.local
